### PR TITLE
Fix wrong quotes, introduced in 9216276b.

### PR DESCRIPTION
**Pull request by kvij**
Didn't save the last changes and introduced breaking changes.

### CODE REVIEW

**Comment by MiLk** [comment]
@tokyowizard 
Did you test #8?
Could you confirm it's ok.
Thank you.

**Comment by ghost** [comment]
I just noticed Peterparks (fork) actually fixed the issue as well in the same matter. Perhaps this is testing enough. Again sorry for introducing the bug.

**Comment by vendamere** [comment]
Yeah, working for me. Sorry couldn't submit a PR without company approval. I thought I would have got it faster.

**Comment by MiLk** [comment]
Released!

Thank you guys.

**Pull request merged**
